import React from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation } from 'swiper/modules';
import 'swiper/swiper-bundle.css'; // Import Swiper styles
import bgShape3 from '../../assets/imgs/bg-shape-3.svg'; // Adjust the path to your assets
import iconLinkedin from '../../assets/imgs/icon-linkedin.svg';
import testimonial1 from '../../assets/imgs/testimonial-1.jpg';
import testimonial2 from '../../assets/imgs/testimonial-2.jpg';
import testimonial3 from '../../assets/imgs/testimonial-3.jpg';
import '../../assets/css/style.css'; // Import your custom CSS
import '../../assets/css/responsive.css'; // Import your responsive CSS

const TestimonialArea = () => {
  return (
    <section className="testimonial-area">
      <div className="custom-container">
        <div className="testimonial-slider-wrap">
          <Swiper
            modules={[Navigation]} // Add Navigation module here
            navigation={{
              nextEl: '.swiper-button-next',
              prevEl: '.swiper-button-prev',
            }}
            className="testimonial-slider"
          >
            <div className="swiper-wrapper">
              <SwiperSlide className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img
                    className="animation-slide-right bg-shape"
                    src={bgShape3}
                    alt="Shape"
                  />
                   <span className="platform-name">
                    <img src={iconLinkedin} alt="Icon" />
                  </span>
                  {/* <h1>
                    Platform helped me to increase my sales and revenue generated by bluebase
                    technologies
                  </h1> */}
                  <p>
                  “Nighwan Technology completely transformed our manufacturing processes with their innovative AI solutions. The results were immediate—efficiency skyrocketed, and we reduced costs significantly. Their team’s expertise and hands-on approach made a huge difference. They truly understand the needs of modern businesses and are an essential partner for our success.”
                  </p>
                  <div className="author-box d-flex align-items-center">
                    {/* <img src={testimonial1} alt="Testimonial" /> */}
                    <div className="author-box-content">
                    <h4>— Rajiv P.</h4>
                    <p>Operations Manager</p>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src={bgShape3} alt="Shape" />
                  <span className="platform-name">
                    <img src={iconLinkedin} alt="Icon" />
                  </span>
                  {/* <h1>
                    Bluebase give the best service and top customer support. Really like to have
                    more projects with you
                  </h1> */}
                  <p>
                  “We implemented Nighwan Technology’s HRMS to streamline our recruitment and human resource management. The system has dramatically improved our efficiency, reducing manual errors and speeding up the hiring process. Their AI-powered tools have made our operations more transparent and data-driven, giving us better control over our workforce management.”
                  </p>
                  <div className="author-box d-flex align-items-center">
                    {/* <img src={testimonial2} alt="Testimonial" /> */}
                    <div className="author-box-content">
                      <h4>— Aisha K.</h4>
                      <p>HR Manager</p>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src={bgShape3} alt="Shape" />
                  <span className="platform-name">
                    <img src={iconLinkedin} alt="Icon" />
                  </span>
                  {/* <h1>
                    We’ve been using bluebase for a few years, It is very simple and easy to
                    approach team and management
                  </h1> */}
                  <p>
                  “Nighwan’s Lean consultancy was a game-changer for our business. They helped us identify inefficiencies and implemented strategies that reduced costs and improved productivity. Their deep understanding of lean principles and AI integration made a real impact. Our bottom line has significantly improved, and we are now operating at peak efficiency.”
                  </p>
                  <div className="author-box d-flex align-items-center">
                    {/* <img src={testimonial3} alt="Testimonial" /> */}
                    <div className="author-box-content">
                      <h4>— Ravi S.</h4>
                      <p>Manufacturing CEO</p>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src={bgShape3} alt="Shape" />
                  <span className="platform-name">
                    <img src={iconLinkedin} alt="Icon" />
                  </span>
                  {/* <h1>
                    We’ve been using bluebase for a few years, It is very simple and easy to
                    approach team and management
                  </h1> */}
                  <p>
                  “Nighwan Technology’s AI-driven e-commerce platform took our online business to the next level. The sales forecasting and data analytics tools allowed us to make informed decisions that boosted our revenue. Their platform is intuitive and scalable, and the support team has been fantastic in helping us grow our brand.”
                  </p>
                  <div className="author-box d-flex align-items-center">
                    {/* <img src={testimonial3} alt="Testimonial" /> */}
                    <div className="author-box-content">
                      <h4>— Anil T.</h4>
                      <p>E-Commerce Business Owner</p>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src={bgShape3} alt="Shape" />
                  <span className="platform-name">
                    <img src={iconLinkedin} alt="Icon" />
                  </span>
                  {/* <h1>
                    We’ve been using bluebase for a few years, It is very simple and easy to
                    approach team and management
                  </h1> */}
                  <p>
                  “We implemented Nighwan’s Transport Management System to optimize our logistics operations, and the results have been remarkable. From route optimization to real-time tracking, the system has made our transportation more efficient, reducing delays and costs. Their expert team was with us every step of the way, ensuring a smooth implementation.”
                  </p>
                  <div className="author-box d-flex align-items-center">
                    {/* <img src={testimonial3} alt="Testimonial" /> */}
                    <div className="author-box-content">
                      <h4>— Meera D.</h4>
                      <p>Logistics Director</p>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
            </div>
          </Swiper>

          {/* Navigation buttons */}
          <div className="swiper-button-prev">
            <i className="iconoir-arrow-left"></i>
          </div>
          <div className="swiper-button-next">
            <i className="iconoir-arrow-right"></i>
          </div>
        </div>
      </div>
    </section>
  );
};

export default TestimonialArea;